myenviroment/perfectcushion/perfectcushion/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('shop/',include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

myenviroment/perfectcushion/shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('',views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),
    ]
    

myenviroment/perfectcushion/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
      name = models.CharField(max_length=250, unique = True)
      slug = models.SlugField(max_length=250, unique = True)
      description = models.TextField(blank=True)
      image = models.ImageField(upload_to='category', blank= True)
        
      class Meta:
         ordering = ('name',)
         verbose_name = 'category'
         verbose_name_plural = 'categories'
         
      def get_url(self):
            return reverse('shop:products_by_category', args=[self.slug])
        
      def __str__(self):
            return '{}'.format(self.name)
        
class Product(models.Model):
        name = models.CharField(max_length=250, unique=True)
        slug = models.SlugField(max_length=250, unique=True)  
        description = models.TextField(blank=True)
        category = models.ForeignKey(Category, on_delete=models.CASCADE)
        price = models.DecimalField(max_digits = 10, decimal_places=2)
        image = models.ImageField(upload_to='product', blank=True)
        stock = models.IntegerField()
        available = models.BooleanField(default=True)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
   
        class Meta:
         ordering = ('name',)
         verbose_name = 'product'
         verbose_name_plural = 'products'
            
        def get_url(self):
            return reverse('shop:ProdCatDetail',args=[self.category.slug, self.slug])
        def __str__(self):
         return '{}'.format(self.name)

myenviroment/perfectcushion/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category,Product

# Create your views here.

def index(request):
    text_var = 'This is my first django webpage app'
    return HttpResponse(text_var)
    
#Category view
def allProdCat(request, c_slug=None):
    c_page = None
    products = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products = Product.objects.filter(category=c_page,available=True)
    else:
        products = Product.objects.all().filter(available=True)
    return render(request,'shop/category.html',{'category':c_page,'products':products})
   
def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product':product})

myenviroment/perfectcushion/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name ="description" content="{% block metadescription %}{% endblock %}">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %} {% endblock %} </title>
</head>
<body>
	<div class="container">
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}
		
	</div>
	
		{% include 'footer.html' %}
		<script src="{% static 'js/jquery-3.4.1.slim.min.js' %}" ></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

myenviroment/perfectcushion/shop/templates/footer.html
<div>

	<p>&copy; Alan Koh .All Right Reserved. </p>
</div>

myenviroment/perfectcushion/shop/templates/header.html
{% load static %}
<header>

	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}"  alt="Perfect Cushion Store"></a>
	</center>
	
</header>

myenviroment/perfectcushion/shop/templates/navbar.html
<nav>
	<ul>
		<li> <a href="{% url 'shop:allProdCat' %}"> All Products </a> </li>
		{% for cat in links %}
			<li> <a href="{{cat.get_url}}">{{cat.name}}</a></li>
		{% endfor %}
		<li> Your Cart()</li>
	</ul>
	
</nav><br>

myenviroment/perfectcushion/shop/templates/shop/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
	{% if category %}
		{{ category.description|truncatewords:155}}
	{% else %}
		Welcome to the cushion store where you can buy comfy and awesome cushions.
	{% endif %}
{% endblock %}

{% block title %}
	{% if category %}
		{{ category.name}} - Perfect Cushion Store	
	{% else %}
		See our Cushion Collection - Perfect CushionStore
	{% endif %}
{% endblock %}

{% block content %}
	<!--Breadcrumb Navigation-->
	 {% if category %}
		<div>
			<div>
				<p><a href="{% url 'shop:allProdCat' %}">"Our Product Collection </a> | {{category.name}}</p>
			</div>
		</div>  
	 {% endif %}
		<div>
	 {% if category %}
			<img src="{{category.image.url}}" alt="{{category.name}}">
		</div>
		<br>
		<div>
			<h1>{{category.name}}</h1>
			<p>{{category.description}}</p>
		</div>
	 {% else %}
			<img src="{% static 'img/banner.jpg' %}" alt="Our Product Collections">
		</div>
		<br>
		
		<div>
			<h1> Our Product Collection</h1>
			<p> Lorem ipsum description of the perfect cushion </p>
		</div>
		{% endif %}
		<div>
			<div>
			{% for product in products %}
				<div>
					<div>
						<a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{product.name}}"></a>
						<div>
							<h4> {{product.name}} </h4>
							<p> RM{{product.price}} </p>
						</div>
					</div>	
				</div>
			{% endfor %}	
			</div>
		</div>
		
{% endblock %}

myenviroment/perfectcushion/shop/templates/shop/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
	{{product.description | truncatewords:155}}
{% endblock %}
{% block title %}
	{{ product.name }} - Perfect Cushion Store
{% endblock %}
{% block content %}
	
	<div>
		<div>
			<p> <a href="{% url 'shop:allProdCat' %}">Home</a> |<a href="{{ product.category.get_url }}">{{product.category}} </a> | {{product.name}} </p>
			
		</div>
		<div> 
			<br>
			<div>
				<div>
					<img src="{{product.image.url}}" alt="{{product.name}}">
					
				</div>
			</div>
			<div>
				<h1> {{product.name}} </h1>
				<p> RM {{product.price}} </p>
				<p> Product Description </p>
				{% if product.stock <= 0 %}
					<p> <b> Out of Stock </b> </p>
				{% else %}
					<a href="">Add to Cart </a>
				{% endif %}
				
				
			</div>
		</div>
	</div>

{% endblock %}